<?php
/* @var $this EquipsController */
/* @var $data Equips */
?>

<tr class="view">

<td class='table-cell'><?php echo CHtml::encode($data->EquipName); ?></td><td class='table-cell'><?php echo CHtml::encode($data->UnitMeasurement_Id); ?></td><td class='table-cell'><?php echo CHtml::encode($data->Supplier_id); ?></td><td class='table-cell'><?php echo CHtml::encode($data->Description); ?></td><td class='table-cell'><?php echo CHtml::encode($data->GroupGood_Id); ?></td><td class='table-cell'><?php echo CHtml::encode($data->SubGroupGood_Id); ?></td>	<?php /*
<td class='table-cell'><?php echo CHtml::encode($data->CategoryGood_Id); ?></td><td class='table-cell'><?php echo CHtml::encode($data->EquipImage); ?></td><td class='table-cell'><?php echo CHtml::encode($data->actp_id); ?></td><td class='table-cell'><?php echo CHtml::encode($data->ctgr_id); ?></td><td class='table-cell'><?php echo CHtml::encode($data->grp_id); ?></td><td class='table-cell'><?php echo CHtml::encode($data->sgrp_id); ?></td><td class='table-cell'><?php echo CHtml::encode($data->discontinued); ?></td><td class='table-cell'><?php echo CHtml::encode($data->SystemType_id); ?></td><td class='table-cell'><?php echo CHtml::encode($data->ServicingTime); ?></td><td class='table-cell'><?php echo CHtml::encode($data->AddressSystem_id); ?></td><td class='table-cell'><?php echo CHtml::encode($data->rate); ?></td><td class='table-cell'><?php echo CHtml::encode($data->must_instruction); ?></td><td class='table-cell'><?php echo CHtml::encode($data->there_instruction); ?></td><td class='table-cell'><?php echo CHtml::encode($data->must_photo); ?></td><td class='table-cell'><?php echo CHtml::encode($data->there_photo); ?></td><td class='table-cell'><?php echo CHtml::encode($data->must_analog); ?></td><td class='table-cell'><?php echo CHtml::encode($data->there_analog); ?></td><td class='table-cell'><?php echo CHtml::encode($data->must_producer); ?></td><td class='table-cell'><?php echo CHtml::encode($data->there_producer); ?></td><td class='table-cell'><?php echo CHtml::encode($data->must_supplier); ?></td><td class='table-cell'><?php echo CHtml::encode($data->there_supplier); ?></td><td class='table-cell'><?php echo CHtml::encode($data->note); ?></td><td class='table-cell'><?php echo CHtml::encode($data->group_id); ?></td><td class='table-cell'><?php echo CHtml::encode($data->Lock); ?></td><td class='table-cell'><?php echo CHtml::encode($data->EmplLock); ?></td><td class='table-cell'><?php echo CHtml::encode($data->DateLock); ?></td><td class='table-cell'><?php echo CHtml::encode($data->EmplCreate); ?></td><td class='table-cell'><?php echo CHtml::encode($data->DateCreate); ?></td><td class='table-cell'><?php echo CHtml::encode($data->EmplChange); ?></td><td class='table-cell'><?php echo CHtml::encode($data->DateChange); ?></td><td class='table-cell'><?php echo CHtml::encode($data->EmplDel); ?></td><td class='table-cell'><?php echo CHtml::encode($data->DelDate); ?></td>	*/ ?>

</tr>