<?php
return array(
	
  /** Роли для таблиц из раздела "Справочники" **/
        'ManagerReference' => array(
            'type' => CAuthItem::TYPE_ROLE,
            'description' => 'ManagerReference',
            'bizRule' => null,
            'data' => null,
            'defaultIndex' => 'reference/index',
            'children' => array(
                'ManagerStreets',
                'ManagerRegions',
                'ManagerJuridicals',
                'ManagerStreetTypes',
                'ManagerServiceTypes',
                'ManagerDocTypes',
                'ManagerAreas',
                'ManagerBanks',
                'ManagerCustomers',
                'ManagerDemandTypes',
                'ManagerDemandPriors',
                'ManagerDelayReasons',
                'ManagerTransferReasons',
                'ManagerSystemTypes',
                'ManagerLoyaltyTypes',
                'ManagerPaymentTypes',
                'ManagerPriceChangeReasons',
                'ManagerJobTypes',
                'ManagerConfirmCancels',
                'ManagerStorages',
                'ManagerWorkTypes',
                'ManagerReceiptReasons',
                'ManagerDebtReasons',
                'ManagerResults',
                'ManagerContactKinds',
                'ManagerContactTypes',
                'ManagerObjectTypes',
                'ManagerComplexityTypes',
                'ManagerCompetitors',
                'ManagerAddressSystems',
                'ManagerNegatives',
                'ManagerEquipGroups',
                'ManagerSystemAvailabilitys',
                'ManagerFormsOfOwnership',
                'ManagerPropForms',
                'ManagerEqipGroups',
                'ManagerEquipAnalog',
                'ManagerEquipCategory',
                'ManagerEquipDetails',
                'ManagerEquipRateDetails',
                'ManagerEquipRates',
                'ManagerEquips',
                'ManagerEquipsHistory',
                'ManagerEquipsRate',
                'ManagerEquipSubgroups',
                'ManagerEquipTypes',
                ),
        ),

        'AdminReference' => array(
            'type' => CAuthItem::TYPE_ROLE,
            'description' => 'AdminReference',
            'bizRule' => null,
            'data' => null,
            'defaultIndex' => 'reference/index',
            'children' => array(
                'AdminStreets',
                'AdminRegions',
                'AdminJuridicals',
                'AdminStreetTypes',
                'AdminServiceTypes',
                'AdminDocTypes',
                'AdminAreas',
                'AdminBanks',
                'AdminCustomers',
                'AdminDemandTypes',
                'AdminDemandPriors',
                'AdminDelayReasons',
                'AdminTransferReasons',
                'AdminSystemTypes',
                'AdminLoyaltyTypes',
                'AdminPaymentTypes',
                'AdminPriceChangeReasons',
                'AdminJobTypes',
                'AdminConfirmCancels',
                'AdminStorages',
                'AdminWorkTypes',
                'AdminReceiptReasons',
                'AdminDebtReasons',
                'AdminResults',
                'AdminContactKinds',
                'AdminContactTypes',
                'AdminObjectTypes',
                'AdminComplexityTypes',
                'AdminCompetitors',
                'AdminAddressSystems',
                'AdminNegatives',
                'AdminEquipGroups',
                'AdminSystemAvailabilitys',
                'AdminFormsOfOwnership',
                'AdminPropForms',
                'AdminEqipGroups',
                'AdminEquipAnalog',
                'AdminEquipCategory',
                'AdminEquipDetails',
                'AdminEquipRateDetails',
                'AdminEquipRates',
                'AdminEquips',
                'AdminEquipsHistory',
                'AdminEquipsRate',
                'AdminEquipSubgroups',
                'AdminEquipTypes',
                ),
        ),

        'UserReference' => array(
            'type' => CAuthItem::TYPE_ROLE,
            'description' => 'UserReference',
            'bizRule' => null,
            'data' => null,
            'defaultIndex' => 'reference/index',

        ),

);