<?php
/* @var $this PropFormsController */
/* @var $data PropForms */
?>

<tr class="view">

<td class='table-cell'><?php echo CHtml::encode($data->FormName); ?></td><td class='table-cell'><?php echo CHtml::encode($data->fown_id); ?></td><td class='table-cell'><?php echo CHtml::encode($data->lph_id); ?></td><td class='table-cell'><?php echo CHtml::encode($data->TaxNumber); ?></td><td class='table-cell'><?php echo CHtml::encode($data->SettlementAccount); ?></td><td class='table-cell'><?php echo CHtml::encode($data->City); ?></td>	<?php /*
<td class='table-cell'><?php echo CHtml::encode($data->bank_id); ?></td><td class='table-cell'><?php echo CHtml::encode($data->jregion); ?></td><td class='table-cell'><?php echo CHtml::encode($data->jarea); ?></td><td class='table-cell'><?php echo CHtml::encode($data->jstreet); ?></td><td class='table-cell'><?php echo CHtml::encode($data->jhouse); ?></td><td class='table-cell'><?php echo CHtml::encode($data->jcorp); ?></td><td class='table-cell'><?php echo CHtml::encode($data->fregion); ?></td><td class='table-cell'><?php echo CHtml::encode($data->farea); ?></td><td class='table-cell'><?php echo CHtml::encode($data->fstreet); ?></td><td class='table-cell'><?php echo CHtml::encode($data->fhouse); ?></td><td class='table-cell'><?php echo CHtml::encode($data->fcorp); ?></td><td class='table-cell'><?php echo CHtml::encode($data->inn); ?></td><td class='table-cell'><?php echo CHtml::encode($data->kpp); ?></td><td class='table-cell'><?php echo CHtml::encode($data->account); ?></td><td class='table-cell'><?php echo CHtml::encode($data->telephone); ?></td><td class='table-cell'><?php echo CHtml::encode($data->post_index); ?></td><td class='table-cell'><?php echo CHtml::encode($data->region_name); ?></td><td class='table-cell'><?php echo CHtml::encode($data->froom); ?></td><td class='table-cell'><?php echo CHtml::encode($data->jroom); ?></td><td class='table-cell'><?php echo CHtml::encode($data->DEBT); ?></td><td class='table-cell'><?php echo CHtml::encode($data->VIP); ?></td><td class='table-cell'><?php echo CHtml::encode($data->sum_price); ?></td><td class='table-cell'><?php echo CHtml::encode($data->sum_appz_price); ?></td><td class='table-cell'><?php echo CHtml::encode($data->Lock); ?></td><td class='table-cell'><?php echo CHtml::encode($data->EmplLock); ?></td><td class='table-cell'><?php echo CHtml::encode($data->DateLock); ?></td><td class='table-cell'><?php echo CHtml::encode($data->EmplChange); ?></td><td class='table-cell'><?php echo CHtml::encode($data->DateChange); ?></td><td class='table-cell'><?php echo CHtml::encode($data->EmplDel); ?></td><td class='table-cell'><?php echo CHtml::encode($data->DelDate); ?></td>	*/ ?>

</tr>